=begin
#ESR Orders API

#API to process orders

OpenAPI spec version: 1.0.0
Contact: tomas.hreha@elder-studios.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DefaultApi)
    end
  end

  # unit tests for change_order_address
  # 
  # change recipient address
  # @param change_order_address change recipient address
  # @param [Hash] opts the optional parameters
  # @return [UploadResponse]
  describe 'change_order_address test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_order_tracking
  # 
  # retrieve order status and tracking information. status 1 is pending, status 3 is shipped, status 5 is complete, status 6 is cancelled
  # @param get_order_tracking check status and tracking
  # @param [Hash] opts the optional parameters
  # @return [TrackingResponse]
  describe 'get_order_tracking test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_order
  # 
  # create order
  # @param upload_order upload order
  # @param [Hash] opts the optional parameters
  # @return [UploadResponse]
  describe 'upload_order test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
