=begin
#ESR Orders API

#API to process orders

OpenAPI spec version: 1.0.0
Contact: tomas.hreha@elder-studios.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/error_model'
require 'swagger_client/models/get_order_tracking'
require 'swagger_client/models/message'
require 'swagger_client/models/messages'
require 'swagger_client/models/set_order_address'
require 'swagger_client/models/set_order_address_login'
require 'swagger_client/models/set_order_address_update_address'
require 'swagger_client/models/tracking_response'
require 'swagger_client/models/upload_order'
require 'swagger_client/models/upload_order_order'
require 'swagger_client/models/upload_order_order_items'
require 'swagger_client/models/upload_order_order_items_item'
require 'swagger_client/models/upload_response'

# APIs
require 'swagger_client/api/default_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
